services:
  database:
    container_name: esus_database
    image: esus_database:1.0.0
    build: database
    environment:
      POSTGRES_DB: esus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: esus
    volumes:
      - esus_pgdata:/var/lib/postgresql/data
    networks:
      - esus_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  webserver:
    container_name: esus_webserver
    image: esus_webserver:5.4.22
    build:
      context: webserver
      args:
        - URL_DOWNLOAD_ESUS=https://arquivos.esusaps.ufsc.br/PEC/e05d0f216b67efe0/5.4.22/eSUS-AB-PEC-5.4.22-Linux64.jar
        - APP_DB_URL
        - APP_DB_USER=postgres
        - APP_DB_PASSWORD=esus
    ports:
      - '8080:8080'
    networks:
      - esus_network
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://localhost:8080"
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
networks:
  esus_network:
    driver: bridge

volumes:
  esus_pgdata:
